#define UNICODE
#define _UNICODE
#include <windows.h>
#include <shellapi.h>
#include <shlobj.h>
#include <tlhelp32.h>

static const COLORREF BG=RGB(19,20,23), SURFACE=RGB(28,30,34), FOOTER=RGB(23,25,28), BORDER=RGB(46,49,55), TEXT=RGB(213,216,221), MUTED=RGB(139,145,155), ACCENT=RGB(166,107,240), ACTIVE=RGB(35,38,43);
static HWND window_handle; static BOOL remove_user_data; static BOOL removing; static HANDLE remove_process; static ULONGLONG remove_started; static WCHAR install_dir[MAX_PATH]; static BOOL axyne_running;

static void box(HDC dc,COLORREF color,int l,int t,int r,int b){HBRUSH brush=CreateSolidBrush(color);RECT rect={l,t,r,b};FillRect(dc,&rect,brush);DeleteObject(brush);}
static void label(HDC dc,const WCHAR *value,int x,int y,int w,int h,COLORREF color,int size,int weight,UINT flags){HFONT font=CreateFontW(-size,0,0,0,weight,FALSE,FALSE,FALSE,DEFAULT_CHARSET,OUT_DEFAULT_PRECIS,CLIP_DEFAULT_PRECIS,CLEARTYPE_QUALITY,DEFAULT_PITCH|FF_DONTCARE,L"Segoe UI");HFONT old=SelectObject(dc,font);SetTextColor(dc,color);SetBkMode(dc,TRANSPARENT);RECT rect={x,y,x+w,y+h};DrawTextW(dc,value,-1,&rect,flags|DT_NOPREFIX);SelectObject(dc,old);DeleteObject(font);}
static void border(HDC dc,int l,int t,int r,int b){HPEN pen=CreatePen(PS_SOLID,1,BORDER);HBRUSH old_brush=SelectObject(dc,GetStockObject(NULL_BRUSH));HPEN old_pen=SelectObject(dc,pen);Rectangle(dc,l,t,r,b);SelectObject(dc,old_pen);SelectObject(dc,old_brush);DeleteObject(pen);}
static void button(HDC dc,const WCHAR *value,int x,int y,int w,BOOL primary){box(dc,primary?ACCENT:ACTIVE,x,y,x+w,y+30);if(!primary)border(dc,x,y,x+w,y+30);label(dc,value,x,y,w,30,primary?BG:TEXT,12,primary?600:400,DT_CENTER|DT_VCENTER|DT_SINGLELINE);}
static void checkbox(HDC dc,int x,int y,BOOL checked,const WCHAR *value){box(dc,checked?ACCENT:SURFACE,x,y,x+13,y+13);border(dc,x,y,x+13,y+13);if(checked){label(dc,L"✓",x,y-2,13,16,BG,11,700,DT_CENTER|DT_VCENTER|DT_SINGLELINE);}label(dc,value,x+24,y-2,440,20,TEXT,12,400,DT_LEFT|DT_TOP);}
static BOOL is_axyne_running(void){HANDLE snapshot=CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS,0);if(snapshot==INVALID_HANDLE_VALUE)return FALSE;PROCESSENTRY32W entry={sizeof(entry)};BOOL running=FALSE;if(Process32FirstW(snapshot,&entry)){do{if(lstrcmpiW(entry.szExeFile,L"axyne.exe")==0){running=TRUE;break;}}while(Process32NextW(snapshot,&entry));}CloseHandle(snapshot);return running;}
static BOOL CALLBACK close_axyne_window_callback(HWND hwnd, LPARAM param){DWORD pid=0;GetWindowThreadProcessId(hwnd,&pid);HANDLE process=OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION,FALSE,pid);if(!process)return TRUE;WCHAR path[MAX_PATH];DWORD size=MAX_PATH;if(QueryFullProcessImageNameW(process,0,path,&size)){WCHAR *name=wcsrchr(path,L'\\');if(name&&lstrcmpiW(name+1,L"axyne.exe")==0){PostMessageW(hwnd,WM_CLOSE,0,0);*(BOOL*)param=TRUE;}}CloseHandle(process);return TRUE;}
static BOOL close_axyne_windows(void){BOOL found=FALSE;EnumWindows(close_axyne_window_callback,(LPARAM)&found);return found;}
static BOOL CALLBACK terminate_axyne_callback(HWND hwnd, LPARAM param){DWORD pid=0;HANDLE process;WCHAR path[MAX_PATH];DWORD size=MAX_PATH;GetWindowThreadProcessId(hwnd,&pid);process=OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION|PROCESS_TERMINATE|SYNCHRONIZE,FALSE,pid);if(!process)return TRUE;if(QueryFullProcessImageNameW(process,0,path,&size)){WCHAR *name=wcsrchr(path,L'\\');if(name&&lstrcmpiW(name+1,L"axyne.exe")==0)TerminateProcess(process,1);}CloseHandle(process);(void)param;return TRUE;}
static BOOL wait_axyne_stopped(void){int i;for(i=0;i<40;++i){if(!is_axyne_running())return FALSE;Sleep(50);}if(is_axyne_running())EnumWindows(terminate_axyne_callback,0);for(i=0;i<20;++i){if(!is_axyne_running())return FALSE;Sleep(50);}return is_axyne_running();}
static void paint(HWND hwnd,HDC dc){SetTimer(hwnd,1,250,NULL);axyne_running=is_axyne_running();box(dc,SURFACE,0,0,560,420);box(dc,BG,1,1,559,33);label(dc,L"A",12,8,16,16,ACCENT,12,700,DT_CENTER|DT_VCENTER|DT_SINGLELINE);label(dc,L"Axyne 제거",38,8,300,18,RGB(196,200,206),12,400,DT_LEFT|DT_TOP);label(dc,L"×",512,5,18,22,TEXT,18,400,DT_CENTER|DT_VCENTER|DT_SINGLELINE);
    if(!removing){
        label(dc,L"Axyne를 제거할까요?",26,56,500,30,RGB(255,255,255),20,700,DT_LEFT|DT_TOP);
        label(dc,L"Axyne와 설치된 구성 요소를 이 컴퓨터에서 제거합니다.",26,101,500,22,MUTED,13,400,DT_LEFT|DT_TOP);
        box(dc,RGB(35,30,43),26,143,533,193);border(dc,26,143,533,193);label(dc,L"!",39,158,16,18,ACCENT,14,700,DT_CENTER|DT_VCENTER|DT_SINGLELINE);label(dc,axyne_running?L"Axyne가 실행 중입니다. 먼저 창을 닫아 주세요.":L"제거를 시작하기 전에 실행 중인 Axyne 창을 닫아 주세요.",67,143,350,50,TEXT,12,400,DT_LEFT|DT_VCENTER|DT_SINGLELINE);if(axyne_running)button(dc,L"프로그램 닫기",412,154,109,FALSE);
        label(dc,L"설치 위치",26,217,500,20,MUTED,12,400,DT_LEFT|DT_TOP);box(dc,SURFACE,26,241,533,273);border(dc,26,241,533,273);label(dc,install_dir,38,248,480,18,TEXT,12,400,DT_LEFT|DT_TOP);
        checkbox(dc,26,298,remove_user_data,L"사용자 설정과 캐시도 함께 제거");
        box(dc,FOOTER,1,363,559,419);border(dc,1,363,559,363);label(dc,L"Axyne 제거 마법사",16,384,330,18,MUTED,11,400,DT_LEFT|DT_TOP);button(dc,L"취소",355,378,84,FALSE);button(dc,L"제거",447,378,96,TRUE);
    }else{
        label(dc,L"Axyne를 제거하는 중입니다",26,56,500,30,RGB(255,255,255),20,700,DT_LEFT|DT_TOP);label(dc,L"설치된 파일과 바로가기를 정리하고 있습니다.",26,101,500,22,MUTED,13,400,DT_LEFT|DT_TOP);label(dc,L"진행률",26,139,400,18,TEXT,12,400,DT_LEFT|DT_TOP);label(dc,L"제거 파일 정리 중...",26,174,450,20,TEXT,12,400,DT_LEFT|DT_TOP);box(dc,SURFACE,26,205,533,213);box(dc,ACCENT,26,205,26+(507*(int)((GetTickCount64()-remove_started)/15)),213);box(dc,RGB(22,23,26),26,230,533,337);border(dc,26,230,533,337);label(dc,L"Axyne.exe",40,246,450,18,MUTED,12,400,DT_LEFT|DT_TOP);label(dc,L"바로가기 및 레지스트리 항목",40,270,450,18,MUTED,12,400,DT_LEFT|DT_TOP);box(dc,FOOTER,1,363,559,419);border(dc,1,363,559,363);label(dc,L"제거 마법사",16,384,400,18,MUTED,11,400,DT_LEFT|DT_TOP);button(dc,L"취소",447,378,96,FALSE);
    }}
static void start_remove(void){WCHAR backend[MAX_PATH];wsprintfW(backend,L"%s\\Uninstall-Backend.exe",install_dir);WCHAR cmd[MAX_PATH*2];wsprintfW(cmd,L"\"%s\" /S",backend);STARTUPINFOW si={sizeof(si)};PROCESS_INFORMATION pi={0};if(CreateProcessW(NULL,cmd,NULL,NULL,FALSE,CREATE_NO_WINDOW,NULL,NULL,&si,&pi)){remove_process=pi.hProcess;CloseHandle(pi.hThread);}remove_started=GetTickCount64();removing=TRUE;SetTimer(window_handle,1,50,NULL);}
static void schedule_self_delete(void){WCHAR self[MAX_PATH];GetModuleFileNameW(NULL,self,MAX_PATH);WCHAR command[MAX_PATH*2];wsprintfW(command,L"/c ping 127.0.0.1 -n 2 >nul & del /f /q \"%s\"",self);SHELLEXECUTEINFOW exec={sizeof(exec)};exec.fMask=SEE_MASK_NOCLOSEPROCESS;exec.lpFile=L"cmd.exe";exec.lpParameters=command;exec.nShow=SW_HIDE;ShellExecuteExW(&exec);}
static LRESULT CALLBACK proc(HWND hwnd,UINT msg,WPARAM wp,LPARAM lp){if(msg==WM_NCHITTEST){POINT p={(int)(short)LOWORD(lp),(int)(short)HIWORD(lp)};ScreenToClient(hwnd,&p);if(p.y<33&&p.x<500)return HTCAPTION;return HTCLIENT;}if(msg==WM_ERASEBKGND)return 1;if(msg==WM_TIMER&&wp==1){DWORD code=STILL_ACTIVE;if(remove_process)GetExitCodeProcess(remove_process,&code);if(code!=STILL_ACTIVE&&GetTickCount64()-remove_started>1200){KillTimer(hwnd,1);if(remove_process){CloseHandle(remove_process);remove_process=NULL;}DestroyWindow(hwnd);}InvalidateRect(hwnd,NULL,FALSE);return 0;}if(msg==WM_LBUTTONUP){int x=(int)(short)LOWORD(lp),y=(int)(short)HIWORD(lp);if(y<33&&x>500){DestroyWindow(hwnd);return 0;}if(!removing&&y>=285&&y<335&&x<500){remove_user_data=!remove_user_data;InvalidateRect(hwnd,NULL,FALSE);}if(!removing&&axyne_running&&y>=143&&y<200&&x>=400){close_axyne_windows();axyne_running=wait_axyne_stopped();InvalidateRect(hwnd,NULL,FALSE);return 0;}if(!removing&&y>=360&&x>=447){if(axyne_running){MessageBoxW(hwnd,L"Axyne가 실행 중입니다. 먼저 프로그램을 닫아 주세요.",L"Axyne 제거",MB_OK|MB_ICONWARNING);return 0;}start_remove();return 0;}if(!removing&&y>=360&&x>=355){DestroyWindow(hwnd);return 0;}return 0;}if(msg==WM_PAINT){PAINTSTRUCT ps;HDC dc=BeginPaint(hwnd,&ps);RECT client;GetClientRect(hwnd,&client);HDC buffer=CreateCompatibleDC(dc);HBITMAP bitmap=CreateCompatibleBitmap(dc,client.right,client.bottom);HBITMAP old=(HBITMAP)SelectObject(buffer,bitmap);paint(hwnd,buffer);BitBlt(dc,0,0,client.right,client.bottom,buffer,0,0,SRCCOPY);SelectObject(buffer,old);DeleteObject(bitmap);DeleteDC(buffer);EndPaint(hwnd,&ps);return 0;}if(msg==WM_DESTROY){if(remove_process)TerminateProcess(remove_process,1);if(removing)schedule_self_delete();PostQuitMessage(0);return 0;}return DefWindowProcW(hwnd,msg,wp,lp);}
int WINAPI wWinMain(HINSTANCE instance,HINSTANCE prev,LPWSTR cmd,int show){(void)prev;(void)cmd;GetModuleFileNameW(NULL,install_dir,MAX_PATH);WCHAR *slash=wcsrchr(install_dir,L'\\');if(slash)*slash=0;axyne_running=is_axyne_running();WNDCLASSW wc={0};wc.hInstance=instance;wc.lpfnWndProc=proc;wc.hCursor=LoadCursor(NULL,IDC_ARROW);wc.hbrBackground=CreateSolidBrush(SURFACE);wc.lpszClassName=L"AxyneUninstallerWindow";wc.hIcon=LoadIconW(instance,MAKEINTRESOURCEW(1));RegisterClassW(&wc);window_handle=CreateWindowExW(WS_EX_APPWINDOW,wc.lpszClassName,L"Axyne 제거",WS_POPUP|WS_MINIMIZEBOX,CW_USEDEFAULT,CW_USEDEFAULT,560,420,NULL,NULL,instance,NULL);if(!window_handle)return 1;SendMessageW(window_handle,WM_SETICON,ICON_BIG,(LPARAM)wc.hIcon);SendMessageW(window_handle,WM_SETICON,ICON_SMALL,(LPARAM)wc.hIcon);ShowWindow(window_handle,show);UpdateWindow(window_handle);MSG msg;while(GetMessageW(&msg,NULL,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}return (int)msg.wParam;}
